services:
  - type: web
    name: flight-price-tracker
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SERPAPI_KEY
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: AVIASALES_TOKEN
        sync: false
